---
- name: Set config output directories
  file:
      path: /var/tmp/mgmt_config
      state: directory

- name: Include device vars
  include_vars: "{{ inventory_hostname }}.yml"

- name: Build device config
  template:
    src: l3_sw.j2
    dest: /var/tmp/mgmt_config/{{ inventory_hostname }}.conf
